### ISSUE TITLE
Add validation for resource schemas

### ISSUE THREAD

**Issue by HumairAK** [operate-first/operations#107]

**Comment by tumido** [comment]
Compare `oc --local=true` , `oc --dry-run=true`, https://www.kubeval.com/ etc

**Comment by tumido** [comment]
I came to a conclusion that `kubeval` is the best solution. After that I actually found out we're not the only ones with the same problem (a very recent article from Andrew from the GitOps team):
https://www.openshift.com/blog/validating-openshift-manifests-in-a-gitops-world

We can either use Andrew's repo here:
https://github.com/sabre1041/k8s-manifest-validation

Or use kubeval on our own instead. Andrew is using Tekton based CI, we probably want to defer this role to prow's presubmit job.

We will also need to generate our own collection of schemas for CRDs so we don't have to ignore them. Andrew already has ArgoCD schemas in his repo, we may want to collaborate on that - if we can provide a centralized community controlled schema store for CRDs that would be ideal.

**Comment by mimotej** [comment]
Issue tracking for validation of resource schemas:

- [ ] Add kubeval to toolbox
- [ ] Script for running kubeval in CI
- [ ] Results are shown in the PR
- [ ] Results show if tests passed or not

**Comment by HumairAK** [comment]
Based on today's sync and the PR here: https://github.com/operate-first/schema-store/pull/1 it seems that we'll be creating a new repo to store the schemas, which is fine. But I would like to avoid having to make a PR to 2 different repositories when adding CRD's, so I'd say let's first use `kubeval` using the `--ignore-missing-schemas` flag, while we get the entire pipeline set up for fetching/updating the apis in a way that it's automated and doesn't add more overhead to making PRs.

**Comment by larsks** [comment]
I was thinking that instead of maintaining a schema repository, we could arrange for CI to have unauthenticated access to the cluster openapi endpoint (e.g., by running a proxy service that would expose the openapi schema without requiring authentication). This would solve a couple of problems:

- We would never have to deal with the schema repository being out-of-date
- We wouldn't need different procedures for adding CRDs via the repository vs. adding CRDs via operator subscriptions

Upon reflection, this idea might be less elegant in the face of multiple clusters.
