### ISSUE TITLE
Discuss how to introduce new users to operations in operate-first 

### ISSUE THREAD

**Issue by HumairAK** [operate-first/operations#394]
Currently if you are not already a part of the operate-first ops team, it can be a bit difficult getting started with operations. 
Areas where I think prevent people from taking part in operations: 

1. Lack of access/visibility to the cluster
2. Not being able to tell which issues are beginner friendly
 
For 2.) one suggestion is that we can create a page on the website that aggregates beginner friendly issues.

We can start with identifying a few issues, label them accordingly, and identify the access they will need.

**Comment by tumido** [comment]
I think we should be default to open and grant SREs `cluster-viewer` role or at least as much of it as possible.
This role should not grant access to `Secret`s, but some other resources which include sensitive data may still be included.

Instead of "Is it secure to grant SREs this level of access?" problem I think we should rather view this as a "If this exposes sensitive data, it's wrong and we should advise users 1) not to put sensitive data there, 2) complain upstream that the data should be in secrets" 

Some resources that may be viewed as problematic that come to my mind right away:
1. Routes with certificates
2. Environment variables which may include credentials in case of workloads like JupyreHub
3. Ceph bucket credentials for local buckets
4. Keycloak client secrets
5. Cert manager certificates
6. Logs

I still think most of those should not be viewed as an blocker issue though, and if we properly communicate that the data may be compromised and leaked to SREs, it is OK.

**Comment by HumairAK** [comment]
Okay so the current `sre` group has these permissions, we can just hand these out to whoever wants to partake in helping with operations. WDYT?
