### ISSUE TITLE
[INCIDENT][smaug/object storage] - Unable to create new buckets or access existing buckets

### ISSUE THREAD

**Issue by larsks** [operate-first/operations#479]
### Clusters Affected

smaug

### Users Affected

All smaug users attempting to consume object storage

### Incident Description

The power shutdown earlier this week appears to have impacted the object storage service (Noobaa) on the Smaug cluster. At the moment it is not possible to create new object buckets, nor is it possible to access data on existing buckets. We are investigating the problem and will post updates to this issue when we have more information.

**Comment by larsks** [comment]
I've opened https://access.redhat.com/support/cases/#/case/03229640 for this incident, @HumairAK is the case owner.

**Comment by HumairAK** [comment]
This should be largely resolved. Though we were never able to determine the root cause. 
The buckets are now being created. There was a bit of delay, however we were able to reduce the delay in creation by increasing the resources attributed to odf. 

Buckets are created as expected, and can be read from and written to.

We have engineers continuing to look into this matter on the stability of odf in smaug, however this no longer incident worthy.

**Comment by HumairAK** [comment]
@guymguym, @dannyzaken and others investigated the odf instanced and provided an analysis on delayed db_cleaner queries which can be found here: https://github.com/noobaa/noobaa-core/issues/7015
